name: Build App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swiftc Sources/LocalConsole/LCManager.swift -o output.o
    - name: Run tests
      run: swift test -v
